sudo: required

services: 
  -docker

before_install:

        - docker build -t $COMMIT .

script:

        - docker run $COMMIT npm run test

after_success:
        - docker tag nodejstest 181098/nodejsdemo:$COMMIT 
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push 181098/nodejsdemo:$COMMIT        
