sudo: required

services: 
  -docker

before_install:

        - docker build -t $TRAVIS_JOB_ID .

script:

        - docker run $TRAVIS_JOB_ID npm run test

after_success:
        - docker tag $TRAVIS_JOB_ID 181098/nodejsdemo:$TRAVIS_JOB_ID 
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push 181098/nodejsdemo:$TRAVIS_JOB_ID        
